### ISSUE TITLE
What happend? We K8s is working, But print error and Couldn't work

### ISSUE THREAD

**Issue by QWQyyy** [kubeshark/kubeshark#1243]
K8s cluster is running
![image](https://user-images.githubusercontent.com/54056797/203505574-29432e15-ad39-443b-8f37-22c62029cbc7.png)

We run kubeshark code "kubeshark tap -A"
it can get all pods name, but print error
Couldn't connect to API server, for more info check logs at /root/.kubeshark/kubeshark_cli.log
![image](https://user-images.githubusercontent.com/54056797/203505686-cb54fdf6-e47a-4efd-9b27-bb5abbb7d3e1.png)

We write PATH before run code, it:
![image](https://user-images.githubusercontent.com/54056797/203506051-3548dc6a-bc02-4a05-88fc-f8e4b79c1112.png)

but not work!
so, we look log:

![image](https://user-images.githubusercontent.com/54056797/203506341-b147d038-97df-4cbf-869b-2fe3b8e5f923.png)

so, How to open 8899 port?

**Comment by mertyildiran** [comment]
@QWQyyy `Couldn't connect to API server` is coming from a health check procedure. We're aware that there is a race condition there. So, please simply try to run `kubeshark tap -A` a few times for now.

I think you're running `kubeshark` command in a remote machine like a VPS. The CLI does port forwarding and opens the page in your browser automatically. If you can't configure `kubectl` on your personal computer then you need to set up the port forwarding manually by yourself.

The `failed to get pods in ns: []` error can be sourced from these missing permissions which Kubeshark requires:

```yaml
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  - services
  verbs:
  - list
  - get
  - create
  - delete
- apiGroups:
  - ""
  - apps
  resources:
  - daemonsets
  verbs:
  - list
  - get
  - create
  - patch
  - delete
```
