### ISSUE TITLE
Command failing with `Error creating resources: insufficient permissions: namespaces is forbidden`

### ISSUE THREAD

**Issue by rajeeshckr** [kubeshark/kubeshark#1283]
**Describe the bug**
Looks like we are getting the below error.
<img width="889" alt="image" src="https://user-images.githubusercontent.com/6300095/209885654-f246e48d-f277-43e9-944f-48387cb58a56.png">

If there is a way to pass in the `-as <username> --as-group <groupname>` to the kubeshark command line, that would be great. Since we have all the permissions defined in the impersonated user and group.

Looks like we could inject these values in here possibly after accepting values through command line.
<img width="980" alt="image" src="https://user-images.githubusercontent.com/6300095/209886248-7e8042b5-4c7d-4991-a510-ae4d86266bc0.png">

**To Reproduce**
1. Run `kubeshark deploy`

**Expected behavior**
Should be succeeded with no error with the impersonated user.

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by rajeeshckr** [comment]
I can achieve this by updating the user information in the kubeconfig file like this. I will close this.

```
users:
- name: myuser-as-admin
  user:
    # Normal credentials here, could be client certs, exec, whatever
    username: myuser
    password: password123

    # Impersonation information below
    as: admin
    as-groups:
      - system:masters
```
