### ISSUE TITLE
Couldn't connect to service && port 8897 connection refused

### ISSUE THREAD

**Issue by Ltd5552** [kubeshark/kubeshark#1312]
**Describe the bug**
i just run `kubeshark tap -n xxx`and cannot reach the UI form chrome, after run `kubeshark check` 
![image](https://user-images.githubusercontent.com/77269387/222361420-80765f2b-5a72-4b56-a6fa-33f07dfc914a.png)
i thought mabe a proxy problem so run with `--proxy-host 0.0.0.0`，but still not work
all k8s resoures work successfully
![image](https://user-images.githubusercontent.com/77269387/222362481-656b9f78-53bb-4c5a-9bbb-1f64ace0a446.png)

but when i check the pod-hub logs find that port 8897 seems doesn't work which similar with https://github.com/kubeshark/kubeshark/issues/1304#issuecomment-1408128200
![image](https://user-images.githubusercontent.com/77269387/222363315-72c2c7cb-b6f6-4a6a-8f39-0c9699c3c893.png)
![image](https://user-images.githubusercontent.com/77269387/222363380-594e2241-bf21-4a0e-88b1-51b52e012043.png)

when i change the front-svc to nodePort, i can reach the UI but no targeted pod
```
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: kubeshark-front
    nodePort: 38899
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kubeshark-front
  sessionAffinity: None
  type: NodePort
```
![image](https://user-images.githubusercontent.com/77269387/222364766-cdc8e5b4-3f54-477c-8570-6cd8a1889904.png)

**Provide more information**
![image](https://user-images.githubusercontent.com/77269387/222366998-7be6e44e-fda0-46c9-b897-209efb362119.png)
cniVersion 0.3.1

**To Reproduce**
1. Run `kubeshark tap`
2. Run `kubeshark check`
3. Run `kubectl logs kubeshark-hub -n kubeshark`

**Expected behavior**
to see the UI and this doesn't happen
![image](https://user-images.githubusercontent.com/77269387/222365978-5f04bb6c-ae04-4d81-94e8-792bc2692c8a.png)

**Desktop (please complete the following information):**
 - OS: win10 <- xshell <-ubuntu20.04
 - Web Browser: Google Chrome

**Additional context**
The k8s cluster and my computer are under the same campus network
