### ISSUE TITLE
Kubeshark Issue in AKS

### ISSUE THREAD

**Issue by BRAVIJSR** [kubeshark/kubeshark#1315]
Getting error while accessing kubeshark in GUI, "Hub and Workers are down and trying to reconnect" in AKS 
We tested in AKS cluster (Ver 1.25.5) with both kubenet and CNI (None) but still issue persists.
Even we have modified ClusterIP to NodePort and Ingress controller but no luck.

We have checked ping and telnet between hub pod and worker pods getting response. 
Would you please suggest.

**Comment by Ltd5552** [comment]
This is very similar to [mine](https://github.com/kubeshark/kubeshark/issues/1312#issue-1606298904)
maybe you can try ` kubectl logs kubeshark-hub -n kubeshark`, and you will find port 8897 connection refused
But i still cannot solve this problem

**Comment by BRAVIJSR** [comment]
yes in hub pod, we are getting following error demon set pods.

Unable to get go user-kernel context [fd: 13]]

**Comment by BRAVIJSR** [comment]
Hi All, 

Please suggest

**Comment by BRAVIJSR** [comment]
We have configured private AKS cluster,  "Network type (plugin)-Kubenet" and "Network Policy-None"

**Comment by Ltd5552** [comment]
hey, I solved my problem for now
It may be due to rancher that the ports of the physical machines established after using `kubeshark tap` could not access each other, and even the local machine could not access the ports, so I later changed the front and hub services to nodeport, and at the same time added a worker's nodeport service.
Like this:
![image](https://user-images.githubusercontent.com/77269387/225521920-0ec53fa3-cdc7-4f50-a651-6aa3c578d97b.png)
Maybe this is not the best way, but it does solve my previous problem, I hope it can help you too.

ps with kubeshark-worker-svc.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: kubeshark
  name: kubeshark-worker
  labels:
    app.kubernetes.io/created-by: kubeshark
    app.kubernetes.io/managed-by: kubeshark
spec:
  ports:
  - port: 8897
    targetPort: 8897
    name: kubeshark-worker
    nodePort: 8897
    protocol: TCP
  selector:
    app: kubeshark-worker
  type: NodePort

```

**Comment by BRAVIJSR** [comment]
Thank you for suggestion, done as suggested but problem persists.

"8897: connect: connection refused" getting error in hub pod logs for worker pod.

**Comment by BRAVIJSR** [comment]
2023-03-16T04:25:40-06:00 WRN watch.go:61 > K8s watch channel closed, restarting watcher...

**Comment by Ltd5552** [comment]
emmm, try `kubectl get all -n kubeshark` to see if all resources are successfully created. And since it is different from the default creation configuration, you need to modify the service to nodeport every time after `kubeshark clean` and `kubeshark tap`.
Also, try `curl localhost:8897` to see if you can access. its ok for me after set up worker-svc , but doesn't work before that.
![image](https://user-images.githubusercontent.com/77269387/225609060-eaf9dde0-af21-4ecb-a171-60a02a7826f4.png)
our k8s clusters are built based on multiple physical machines + rancher. According to my situation and understanding, it should be accessible after that setting. But I am not sure about the situation of AKS, is the `8897` port of the cloud service opened?

**Comment by BRAVIJSR** [comment]
Yes we always start kubeshark tap -A post execute kubeshark clean.

NAME                                    READY   STATUS    RESTARTS   AGE
pod/kubeshark-front                     1/1     Running   0          39m
pod/kubeshark-hub                       1/1     Running   0          39m
pod/kubeshark-worker-daemon-set-6nvjw   1/1     Running   0          39m
pod/kubeshark-worker-daemon-set-wcwqm   1/1     Running   0          39m

NAME                       TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/kubeshark-front    NodePort   10.1.121.140   <none>        80:30356/TCP     39m
service/kubeshark-hub      NodePort   10.1.147.118   <none>        80:32116/TCP     39m
service/kubeshark-worker   NodePort   10.1.195.3     <none>        8897:31944/TCP   26m

NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/kubeshark-worker-daemon-set   2         2         2       2            2           <none>          39m

curl the worker nodes getting response "It's running" even login into kubeshark-hub and kubeshark-front pods able to telnet worker pods with port 8897 
but while trying from kubeshark-front to kubeshark-hub telnet on port 8897 not responding.

Am bother about network plugin "kubenet" (in AKS)is it support or not?

**Comment by BRAVIJSR** [comment]
Please suggest.

**Comment by alongir** [comment]
@BRAVIJSR in all likelihood, connection between the workers and the hub machines is abstracted. 
If the problem persists, I can offer jumping on a quick call to debug. Feel free to reach out to me on Slack and we can find time.

**Comment by BRAVIJSR** [comment]
okay please confirm ur availability and mail id

**Comment by lirany1** [comment]
I got 
```
kubectl apply -f kubeshark-worker-svc.yaml 
The Service "kubeshark-worker" is invalid: spec.ports[0].nodePort: Invalid value: 8897: provided port is not in the valid range. The range of valid ports is 30000-32767
```

**Comment by mertyildiran** [comment]
@lirany1 please try changing `port` of `worker` in [`config.yaml`](https://docs.kubeshark.co/en/config):

```yaml
tap:
    proxy:
        worker:
            port: 8897
            srvport: 8897
        hub:
            port: 8898
            srvport: 80
        front:
            port: 8899
            srvport: 80
        host: 127.0.0.1
```

to something between your accepted range `30000-32767`.

**Comment by lirany1** [comment]
> @lirany1 please try changing `port` of `worker` in [`config.yaml`](https://docs.kubeshark.co/en/config):
> 
> ```yaml
> tap:
>     proxy:
>         worker:
>             port: 8897
>             srvport: 8897
>         hub:
>             port: 8898
>             srvport: 80
>         front:
>             port: 8899
>             srvport: 80
>         host: 127.0.0.1
> ```
> 
> to something between your accepted range `30000-32767`.

I tried:

```
apiVersion: v1
kind: Service
metadata:
  namespace: kubeshark
  name: kubeshark-worker
  labels:
    app.kubernetes.io/created-by: kubeshark
    app.kubernetes.io/managed-by: kubeshark
spec:
  ports:
  - port: 30001
    targetPort: 30001
    name: kubeshark-worker
    nodePort: 30001
    protocol: TCP
  selector:
    app: kubeshark-worker
  type: NodePort
```

```
kubectl apply -f kubeshark-worker-svc.yaml 
service/kubeshark-worker created
kubectl get svc -n kubeshark                 
NAME               TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
kubeshark-front    NodePort   10.110.208.68    <none>        80:32300/TCP      15m
kubeshark-hub      NodePort   10.110.208.126   <none>        80:32077/TCP      15m
kubeshark-worker   NodePort   10.110.208.13    <none>        30001:30001/TCP   14s
```

but still the same :(
BTW i am using k3s by rancher
