### ISSUE TITLE
Stable deployment accessible using  ingress

### ISSUE THREAD

**Issue by abrarcv170** [kubeshark/kubeshark#1332]
### Contact Details

cvabrar170@gmail.com

### Is your feature request related to a problem? Please describe.

```
kubectl get svc -n kubeshark 
NAME              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kubeshark-front   ClusterIP   100.66.77.90     <none>        80/TCP    19h
kubeshark-hub     ClusterIP   100.66.139.123   <none>        80/TCP    19h
```
I have tried to expose the kubeshark-front  service using nginx ingress, but it is not working as expected  because the UI is trying to access the hub on localhost, so I created an ingress for the hub and changed the hub host and port env on the kubeshark-front pod, after it ends up with CORS error 
```
spec:
  containers:
  - env:
    - name: REACT_APP_DEFAULT_FILTER
      value: ' '
    - name: REACT_APP_HUB_HOST
      value: "kubeshark-hub.test.com"
    - name: REACT_APP_HUB_PORT
      value: "80"
    image: docker.io/kubeshark/front:latest
```
I think it is really important to provide stable k8s deployment with ingress, so anyone from the team can access the kubeshark using the ingress URL.

### Describe the solution you'd like to see

Provide helm chart for kubeshark deployment 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
